In [2]:
!conda install matplotlib seaborn -y

Solving environment: ...working... done

# All requested packages already installed.



In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
# фиксируем ядро генератора для повторяемости случайности
np.random.seed(42)
# грузим данные для алгоритма
data = load_iris()

# случайно выбираем 80% данных для обучения
train_idx = np.random.choice(
    np.arange(data['data'].shape[0]), 
    size=int(data['data'].shape[0] * 0.8), 
    replace=False
)
# остальные данные уйдут на валидацию модели
test_idx = np.array([i for i in range(data['data'].shape[0]) if i not in train_idx])
# признаки в данных
train_X = data['data'][train_idx]
test_X = data['data'][test_idx]
# ответы в данных
train_y = data['target'][train_idx]
test_y = data['target'][test_idx]

Тут и далее мы считаем 
- train - данные для тренировки
- test - данные для тестирования

- X - матрица признаков в данных, каждая строка матрицы представляет собой отдельную точку в пространстве со значением координат по столбцам
- y - классы каждой из точек в данных

In [7]:
# координаты первой точки и ее класс
print(train_X[0])
print(train_y[0])

[6.1 2.8 4.7 1.2]
1


In [10]:
# первые 5 точек и их координаты
train_X[:5]

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4]])

In [11]:
# класс первых 5 точек
train_y[:5]

array([1, 0, 2, 1, 1])

<img src="./img/knn.png">

In [13]:
class KNN:

    def __init__(self):
        self.X = None
        self.y = None

    def calc_metric(self, vector):
        # Посчитать растояние от каждой точки в данных до данного вектора
        pass

    def get_closest_index(self, distances):
        # возвращает индекс ближайшей точки
        pass

    def fit(self, X, y):
        # запомнить данные для объекта класса
        pass

    def predict(self, X):
        # предсказать класс каждой точки из X
        result = list()
        for i in range(X.shape[0]):
            vector = X[i]
            distances = self.calc_metric(vector)
            idx = self.get_closest_index(distances)
            closest_class = None # найти класс ближайшего объекта
            result.append(closest_class)
        return result