# Numpy

- numpy - это библиотека для работы с многомерными массивами
- numpy это python обертка для быстрых операций для линейной алгебры над архитектурами lapack, blas
- lapack, blas написаны на более низкоуровневых языках чем Python (С++, Fortran)

In [1]:
# установим нужные библиотеки
!conda install numpy scikit-learn -y

Solving environment: ...working... done

# All requested packages already installed.



In [2]:
import numpy as np # стандартная запись импорта numpy
from sklearn.datasets import load_iris # данные цветков iris

In [3]:
# созданим объект с данными
dataset = load_iris()

In [4]:
X = dataset['data']
y = dataset['target']

In [6]:
# тип данных для экспериментов массив numpy
type(X), type(y)

(numpy.ndarray, numpy.ndarray)

In [26]:
# посмотрим размер массивов
print(f"Двумерный массив X: {X.shape}, {X.ndim}")
print(f"Одномерный массив y: {y.shape}, {y.ndim}")

Двумерный массив X: (150, 4), 2
Одномерный массив y: (150,), 1


In [25]:
# посмотрим количество элементов массивов
print(f"Двумерный массив X: {X.size}")
print(f"Одномерный массив y: {y.size}")

Двумерный массив X: 600
Одномерный массив y: 150


## Создание массива

основной класс данной библиотеки np.ndarray 

данный массив может иметь любую размерность и его возможно создать с помощью обьектов sequence (НЕ mapping!) и вызова np.array

In [10]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
np.array((1, 2, 3))

array([1, 2, 3])

In [13]:
def f(n):
    for i in range(n):
        yield i ** 2

In [16]:
# генераторы не подходят
np.array(f(5))

array(<generator object f at 0x0000022B53272970>, dtype=object)

In [20]:
# генераторы не подходят
np.array((i**2 for i in range(10)))

array(<generator object <genexpr> at 0x0000022B532735F0>, dtype=object)

In [21]:
# mapping тоже не подходит
np.array({1, 2})

array({1, 2}, dtype=object)

In [22]:
# mapping тоже не подходит
np.array({1:1, 2:2})

array({1: 1, 2: 2}, dtype=object)

In [28]:
# многомерные массивы создаются из sequence of sequnce с одинаковым размером!
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [41]:
# многомерные массивы создаются из sequence of sequnce с одинаковым размером!
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"количество измерений может быть любое {a.ndim}")
a

количество измерений может быть любое 3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
# многомерные массивы создаются из sequence of sequnce с одинаковым размером!
np.array([[1, 2], [4]])

C:\Users\ANTON~1.NES\AppData\Local\Temp/ipykernel_9096/2814081267.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1, 2], [4]])


array([list([1, 2]), list([4])], dtype=object)

In [31]:
# многомерные массивы создаются из sequence of sequnce с одинаковым размером! (можно создать массив объектов)
np.array([[1, 2], [4]], dtype="object")

array([list([1, 2]), list([4])], dtype=object)

In [36]:
# все объекты в массиве будут приведены к одному типу, самый общий тип object (не поддерживает вычисления)
np.array([1, "asd", None])

array([1, 'asd', None], dtype=object)

In [37]:
# тип можно специфицировать
np.array(["1", "2"], dtype="float")

array([1., 2.])

In [38]:
# тип можно специфицировать и даже задать размер в байтах
np.array(["1", "2"], dtype=np.float16)

array([1., 2.], dtype=float16)

In [52]:
# есть аналог range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# есть аналог range
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [62]:
# есть аналог range
np.arange(5, 10, 2, dtype="float")

array([5., 7., 9.])

In [72]:
# можно создать числа от и до с определенным количеством
np.linspace(0, 100, 11, dtype=np.int8)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int8)

In [77]:
# можно создать числа от и до с определенным количеством
np.linspace(0, 100, 21, dtype=np.int8)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100], dtype=int8)

In [87]:
# создать еденичный массив
np.ones((10, ))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
# создать еденичный массив
np.ones((10, 5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [102]:
# создать еденичный массив
np.ones((2, 2, 2, 2), dtype=np.int32)

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [112]:
# создать нулевой массив
np.zeros((2, 2, 2, 2), dtype=np.int32)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]])

In [117]:
# создать массив с определенным числом
np.full((2, 2, 2, 2), 5, dtype=np.int32)

array([[[[5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5]]],


       [[[5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5]]]])

In [122]:
# сделать нулевой, едичный, заполненный массив размером как другой массив
np.zeros_like(X)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [127]:
np.full_like(y, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [132]:
# и даже создать массив из ничего нужного размера
np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [147]:
# и даже создать массив из ничего нужного размера (на самом деле он пустой, баг отображения)
b = np.empty_like(y)
print(b.sum())
b

-1768515946


array([16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843009,
       16843009, 16843009, 16843009, 16843009, 16843009, 16843

In [153]:
# можно создавать массивы случайных чисел
np.random.randint(0, 10, (2, 2))

array([[0, 0],
       [5, 2]])

In [165]:
# можно создавать массивы случайных чисел из распределения стандартного нормального
np.random.randn(2, 2)

array([[-1.33093837, -0.46076235],
       [-0.34813679,  1.97204058]])

In [189]:
# можно создавать массивы случайных чисел из распределения нормального
np.random.normal(2, 5, (20, ))

array([11.19492423,  3.03448035,  7.28242325,  8.28923377,  8.46149403,
       -1.32747888,  0.56684908, -3.67333075,  1.3655405 ,  4.27684219,
       12.87780912,  3.627575  , -9.61502413,  0.61777183,  3.73422463,
       -3.48707698,  4.20564192,  8.940894  ,  5.88935406, -3.33427563])

In [195]:
# можно создавать массивы случайных чисел из распределения равномерного
np.random.uniform(2, 5, (20, ))

array([4.42658205, 4.89813359, 2.2419042 , 3.64516802, 2.26223576,
       3.10805862, 2.76934107, 4.79016296, 4.76602178, 3.72193153,
       2.11428906, 2.91854601, 2.56572919, 4.44268296, 3.17199244,
       2.23088691, 4.69755587, 4.3461396 , 4.23311369, 4.67141442])

In [201]:
# а еще можно менять размерность массива
y.reshape(30, 5)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

## Индексирование массива

индексация проводится по осям вдоль каждого измерения:

<img src="./img/axis.png">

In [211]:
#разделение между осями это ","
x_reshaped = X.reshape(10, 10, 6)
x_reshaped[1, 1, 1]

0.4

In [212]:
# ":" возвращает все элементы оси
X[0, :]

array([5.1, 3.5, 1.4, 0.2])

In [213]:
# можно пользовать slice
X[1:10:2, :]

array([[4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [214]:
# использование None, np.newaxis добавит новое измерение
X[0, :, None]

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [215]:
# использование None, np.newaxis добавит новое измерение
X[0, :, np.newaxis]

array([[5.1],
       [3.5],
       [1.4],
       [0.2]])

In [217]:
# индекс может быть другим массивом
i = np.array([2, 3, 5])
X[i, 0]

array([4.7, 4.6, 5.4])

In [220]:
# индекс может быть другим массивом
ii = np.arange(0, 3)
X[i, ii]

array([4.7, 3.1, 1.7])

In [222]:
# можем использовать логический индекс
y[y == 2]

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [223]:
# можем использовать логический индекс
y[(y == 2) | (y == 0)]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [224]:
# можем использовать логический индекс
y[(y < 2) & (y > 0)]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [225]:
# np.where вернет индексы где сравнение возвращает True
np.where((y < 2) & (y > 0))

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       dtype=int64),)

## Математические операции с массивами

In [226]:
# можно складывать, умножать, делить массивы у которых совпадают одна или более размерностей и другие размерности равны 1
# reshape -1 перенесет не используемые размерности в ту где он стоит
X + y.reshape(-1, 1)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [228]:
# размерность не совпала
X * y

ValueError: operands could not be broadcast together with shapes (150,4) (150,) 

In [229]:
X / np.arange(1, 5).reshape(1, -1)

array([[5.1       , 1.75      , 0.46666667, 0.05      ],
       [4.9       , 1.5       , 0.46666667, 0.05      ],
       [4.7       , 1.6       , 0.43333333, 0.05      ],
       [4.6       , 1.55      , 0.5       , 0.05      ],
       [5.        , 1.8       , 0.46666667, 0.05      ],
       [5.4       , 1.95      , 0.56666667, 0.1       ],
       [4.6       , 1.7       , 0.46666667, 0.075     ],
       [5.        , 1.7       , 0.5       , 0.05      ],
       [4.4       , 1.45      , 0.46666667, 0.05      ],
       [4.9       , 1.55      , 0.5       , 0.025     ],
       [5.4       , 1.85      , 0.5       , 0.05      ],
       [4.8       , 1.7       , 0.53333333, 0.05      ],
       [4.8       , 1.5       , 0.46666667, 0.025     ],
       [4.3       , 1.5       , 0.36666667, 0.025     ],
       [5.8       , 2.        , 0.4       , 0.05      ],
       [5.7       , 2.2       , 0.5       , 0.1       ],
       [5.4       , 1.95      , 0.43333333, 0.1       ],
       [5.1       , 1.75      ,

In [230]:
# можем искать среднее, сумму, стандарное отклонение и многое другое для массива
print(X.sum())
print(y.std())

2078.7
0.816496580927726


In [231]:
# складывать массивы со скалярами
y + 10

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [234]:
# смотреть статистики вдоль осей
print(x_reshaped.mean((0, 1)))
print(x_reshaped.mean((1,)))

[4.787 2.133 4.791 2.089 4.824 2.163]
[[3.09 1.7  3.23 1.83 3.18 1.79]
 [3.33 2.01 3.34 1.83 3.33 1.93]
 [3.26 1.9  3.13 1.74 3.24 1.83]
 [4.49 1.96 4.39 1.92 4.8  2.18]
 [5.   1.97 5.29 1.97 5.05 2.11]
 [5.06 2.01 5.19 2.04 5.25 2.17]
 [5.37 2.19 5.08 2.07 5.26 2.24]
 [6.25 2.57 6.15 2.42 5.99 2.4 ]
 [5.97 2.38 6.21 2.49 6.24 2.4 ]
 [6.05 2.64 5.9  2.58 5.9  2.58]]


In [236]:
# более сложные математические операции так же доступны и для массивов, поэлементно и для чисел отдельно
print(np.exp(y))
print(np.log(10))

[1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183
 2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 2.7

In [237]:
# массивы можно транспонировать
print(X.shape)
print(X.T.shape)

(150, 4)
(4, 150)


In [238]:
# и главное делать матричное умножение (не забывайте про правила!)
X.dot(y)

ValueError: shapes (150,4) and (150,) not aligned: 4 (dim 1) != 150 (dim 0)

In [240]:
# и главное делать матричное умножение (не забывайте про правила!)
X.T.dot(y)

array([955.6, 435.9, 768.2, 268.9])

## Другие полезные функции

In [241]:
 # сортировка массива по умолчанию для последней оси
np.sort(X)

array([[0.2, 1.4, 3.5, 5.1],
       [0.2, 1.4, 3. , 4.9],
       [0.2, 1.3, 3.2, 4.7],
       [0.2, 1.5, 3.1, 4.6],
       [0.2, 1.4, 3.6, 5. ],
       [0.4, 1.7, 3.9, 5.4],
       [0.3, 1.4, 3.4, 4.6],
       [0.2, 1.5, 3.4, 5. ],
       [0.2, 1.4, 2.9, 4.4],
       [0.1, 1.5, 3.1, 4.9],
       [0.2, 1.5, 3.7, 5.4],
       [0.2, 1.6, 3.4, 4.8],
       [0.1, 1.4, 3. , 4.8],
       [0.1, 1.1, 3. , 4.3],
       [0.2, 1.2, 4. , 5.8],
       [0.4, 1.5, 4.4, 5.7],
       [0.4, 1.3, 3.9, 5.4],
       [0.3, 1.4, 3.5, 5.1],
       [0.3, 1.7, 3.8, 5.7],
       [0.3, 1.5, 3.8, 5.1],
       [0.2, 1.7, 3.4, 5.4],
       [0.4, 1.5, 3.7, 5.1],
       [0.2, 1. , 3.6, 4.6],
       [0.5, 1.7, 3.3, 5.1],
       [0.2, 1.9, 3.4, 4.8],
       [0.2, 1.6, 3. , 5. ],
       [0.4, 1.6, 3.4, 5. ],
       [0.2, 1.5, 3.5, 5.2],
       [0.2, 1.4, 3.4, 5.2],
       [0.2, 1.6, 3.2, 4.7],
       [0.2, 1.6, 3.1, 4.8],
       [0.4, 1.5, 3.4, 5.4],
       [0.1, 1.5, 4.1, 5.2],
       [0.2, 1.4, 4.2, 5.5],
       [0.2, 1

In [242]:
np.sort(X, axis=0)

array([[4.3, 2. , 1. , 0.1],
       [4.4, 2.2, 1.1, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.4, 2.2, 1.2, 0.1],
       [4.5, 2.3, 1.3, 0.1],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.3, 1.3, 0.2],
       [4.6, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.7, 2.4, 1.3, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.8, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.5, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [4.9, 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.6, 1.4, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5. , 2.7, 1.5, 0.2],
       [5.1, 2.7, 1.5, 0.2],
       [5.1, 2.8, 1.5, 0.2],
       [5.1, 2

In [244]:
# порядок индексов в отсортированном массиве
np.argsort(X) 

array([[3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2, 1, 0],
       [3, 2,

In [245]:
# l2 норма массива
np.linalg.norm(X) 

97.66928892952994

In [246]:
 # оси так же могут быть специфированы для l2 нормы
np.linalg.norm(X, axis=1)

array([ 6.34507683,  5.91692488,  5.83609458,  5.7497826 ,  6.32139225,
        6.88621812,  5.8966092 ,  6.23297682,  5.45618915,  5.98999165,
        6.71863081,  6.09918027,  5.83180932,  5.35817133,  7.14982517,
        7.36613874,  6.79852925,  6.34901567,  7.06470098,  6.54140658,
        6.60681466,  6.48922183,  5.92958683,  6.32771681,  6.18465844,
        6.04979338,  6.26737585,  6.44825558,  6.37181293,  5.91016074,
        5.93717104,  6.56734345,  6.79043445,  7.06328535,  5.99249531,
        6.05970296,  6.65056389,  6.2401923 ,  5.48543526,  6.31347765,
        6.24739946,  5.22685374,  5.59732079,  6.33798075,  6.64981203,
        5.83866423,  6.56124988,  5.77927331,  6.63852393,  6.15548536,
        9.12633552,  8.58487041,  9.13673902,  7.29588925,  8.5732141 ,
        7.89113427,  8.67352293,  6.45445583,  8.64985549,  7.17635005,
        6.5       ,  7.98122798,  7.60526134,  8.3468557 ,  7.37699126,
        8.70746806,  7.92842986,  7.6642025 ,  8.11048704,  7.35

In [249]:
# обратная матрица, матрица не должна быть линейно зависимой
np.linalg.inv(
    np.arange(9).
    reshape(3, 3)
) 

LinAlgError: Singular matrix

In [255]:
# обратная матрица, матрица не должна быть линейно зависимой
b = np.arange(1, 10).reshape(3, 3)  * np.eye(3)
b_inv = np.linalg.inv(b)
b_inv 

array([[1.        , 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.11111111]])

In [256]:
b_inv.dot(b)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Полезные материалы

numpy manual https://docs.scipy.org/doc/numpy/index.html

матричное умножение https://ru.wikipedia.org/wiki/%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86

обратная матрица https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0

еденичная матрица https://ru.wikipedia.org/wiki/%D0%95%D0%B4%D0%B8%D0%BD%D0%B8%D1%87%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0