In [1]:
import numpy as np

In [2]:
!ls /

bin			    etc     media		      root  tools
boot			    home    mnt			      run   usr
content			    lib     NGC-DL-CONTAINER-LICENSE  sbin  var
cuda-keyring_1.0-1_all.deb  lib32   opt			      srv
datalab			    lib64   proc		      sys
dev			    libx32  python-apt		      tmp


In [3]:
a = np.random.randint(0, 255, size=(512, 640, 3))

In [4]:
a.shape # размер массива

(512, 640, 3)

In [5]:
a.size # количество элементов

983040

In [6]:
a[0, 1, 2] # индексы через запятую, индексов столько сколько чисел в shape

170

In [7]:
a[0, :, 2] # вся строчка :

array([150, 170, 234,  38,  89,  22, 133,  42, 235, 122, 217, 155, 125,
        25,  71,  96, 222, 178,  70,  11, 113,  85, 205, 103, 223, 232,
       180, 244,  62, 232, 181,   3,  54, 107, 180,  71, 146, 161, 237,
        13, 170, 154, 150, 218,  22, 121,  94,  81, 207, 180, 204,  35,
       183, 193, 194, 242, 178,   6, 167, 202,  24, 141,  71,  17, 215,
       251,  18, 245, 235,  21,  89,  14, 146, 115, 213,  54, 118, 237,
       177,  25, 103,  51, 114,  95, 110,  47, 101, 247, 141, 191,  58,
       192, 141, 153, 215,  23, 148, 167, 208,  20,  54, 123,  68, 120,
       103,  30, 153,  27,  52,  91,  60, 242, 154,  59, 102, 239, 175,
        29, 196, 119, 157, 228, 220,  55, 138, 197,  27, 244,  31,  10,
       164, 197,  25, 117, 194,  70,  31, 175, 133, 227, 136,   7, 146,
       216,  75,  71, 221,  52, 249,  16,  11, 125, 130, 214,  92,  10,
       108, 128, 171,  43, 188,  69, 202, 137, 159, 133, 150,  72,  46,
       209, 250, 167, 118, 128, 158, 124, 172,  16, 103,  67,  2

In [8]:
a[0, 1, 0:2] # каждое отдельное измеренеие умеет индексироваться как list

array([16, 92])

In [9]:
a[1:10:2, 1, 0:2] # возвращается столько измерений сколько слайсов

array([[ 99, 224],
       [243,  93],
       [201,  91],
       [ 97, 200],
       [ 37,  57]])

In [10]:
a[[1, 3, 5], 1, 2] # индексирование массивом возращает элементы которые указаны в массиве

array([239,   8, 116])

In [11]:
a[[1, 4, 5], [6, 20, 44], 1] # массив будет на любой позиции

array([197, 180,  90])

In [12]:
a[[1, 4, 5], [6, 20], 1] # размер массивом должен быть одинаков

IndexError: ignored

In [13]:
a > 127 # булева операция применится к каждому элементу

array([[[False, False,  True],
        [False, False,  True],
        [False,  True,  True],
        ...,
        [False, False, False],
        [False,  True, False],
        [ True, False, False]],

       [[ True,  True, False],
        [False,  True,  True],
        [ True, False,  True],
        ...,
        [ True,  True, False],
        [ True, False, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False, False],
        [False, False,  True],
        ...,
        [False, False,  True],
        [False, False, False],
        [False, False,  True]],

       ...,

       [[ True, False,  True],
        [False, False, False],
        [False,  True,  True],
        ...,
        [False,  True,  True],
        [ True, False,  True],
        [False, False, False]],

       [[ True, False, False],
        [False, False, False],
        [ True, False,  True],
        ...,
        [False, False,  True],
        [ True, False,  True],
        [False,

In [14]:
a[a > 127] # булево индексирование вернет все элементы которые True одномерным массивом

array([150, 170, 208, ..., 230, 242, 146])

In [15]:
b = np.random.randint(0, 255, size=(4, 5))

In [16]:
b

array([[ 99,  50, 212, 242,  93],
       [ 60,  92,  47,   0, 115],
       [192, 227,   0, 140, 138],
       [213, 207, 222, 181, 228]])

In [17]:
b[0, 1] += 5 # индексирование возвращает ссылки

In [20]:
b

array([[ 99,  55, 212, 242,  93],
       [ 60,  92,  47,   0, 115],
       [192, 227,   0, 420, 138],
       [213, 207, 222, 724, 228]])

In [19]:
b[:, 3] *= np.array([1, 2, 3, 4]) # можно изменить весь столбец/строку выполнив векторную операцию

In [21]:
b[:, 3] *= np.array([1, 2, 3])

ValueError: ignored

In [22]:
np.where(b > 127) # возвращает индексы элементов которые удовлетворяют условию, каждый из массиво это индекс по своей оси

(array([0, 0, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([2, 3, 0, 1, 3, 4, 0, 1, 2, 3, 4]))

In [23]:
np.where(a > 127)

(array([  0,   0,   0, ..., 511, 511, 511]),
 array([  0,   1,   2, ..., 639, 639, 639]),
 array([2, 2, 1, ..., 0, 1, 2]))

In [25]:
(b > 127) & (b < 200)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False]])

In [26]:
(b > 127) | (b < 200)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [27]:
a.shape

(512, 640, 3)

In [28]:
a.mean() # среднее

127.02087809244792

In [29]:
a.mean(axis=(1, 2)).shape # какие оси передаются те и схлопываются

(512,)

In [30]:
a.mean(axis=(0, 2)).shape

(640,)

In [31]:
a.mean(axis=(0, 1))

array([126.87731934, 127.16871643, 127.01659851])

In [32]:
a.mean(axis=1).shape

(512, 3)

In [38]:
a.std(axis=(0, 1)) # стандартное отклонение

array([73.57182119, 73.61476523, 73.56197037])

In [39]:
a.sum()

124866604

In [40]:
np.median(a, axis=(0, 1)) # больше 50% данных и меньше 50%

array([127., 127., 127.])

In [41]:
np.quantile(a, 0.75, axis=(0, 1)) # больше 25% данных и меньше 75%

array([190., 191., 191.])

In [42]:
np.sort(a)

array([[[ 87, 122, 150],
        [ 16,  92, 170],
        [ 52, 208, 234],
        ...,
        [  9,  26,  66],
        [  3,  45, 144],
        [  9,  49, 129]],

       [[  2, 135, 193],
        [ 99, 224, 239],
        [ 88, 224, 232],
        ...,
        [ 23, 144, 168],
        [  4,  23, 202],
        [  0, 155, 232]],

       [[ 39, 113, 234],
        [ 32, 127, 180],
        [ 60,  86, 157],
        ...,
        [ 19,  22, 253],
        [ 25,  96, 125],
        [  3,  10, 225]],

       ...,

       [[ 92, 222, 253],
        [ 13,  99, 126],
        [ 87, 143, 163],
        ...,
        [ 54, 205, 242],
        [  0, 136, 218],
        [ 27,  36,  40]],

       [[ 42,  93, 161],
        [121, 124, 126],
        [111, 161, 175],
        ...,
        [ 17,  36, 186],
        [ 81, 160, 226],
        [ 18, 173, 203]],

       [[ 54,  98, 126],
        [ 27, 157, 232],
        [ 36,  89, 199],
        ...,
        [  9, 109, 240],
        [ 45,  84, 183],
        [146, 230, 242]]

In [43]:
np.sort(a, axis=1) # сортировать можно вдоль одной оси

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   1,   1],
        ...,
        [252, 253, 254],
        [252, 254, 254],
        [253, 254, 254]],

       [[  0,   0,   0],
        [  0,   1,   0],
        [  1,   1,   0],
        ...,
        [253, 253, 253],
        [253, 254, 254],
        [254, 254, 254]],

       [[  0,   0,   0],
        [  1,   1,   0],
        [  1,   2,   0],
        ...,
        [253, 253, 253],
        [253, 254, 254],
        [254, 254, 254]],

       ...,

       [[  0,   0,   1],
        [  1,   0,   2],
        [  1,   1,   2],
        ...,
        [253, 254, 253],
        [253, 254, 254],
        [254, 254, 254]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   1],
        ...,
        [254, 252, 254],
        [254, 252, 254],
        [254, 253, 254]],

       [[  2,   0,   0],
        [  2,   0,   0],
        [  2,   1,   0],
        ...,
        [253, 252, 253],
        [254, 252, 253],
        [254, 254, 254]]

In [44]:
b.ravel() # разворачивает массив в одномерный вектор

array([ 99,  55, 212, 242,  93,  60,  92,  47,   0, 115, 192, 227,   0,
       420, 138, 213, 207, 222, 724, 228])

In [47]:
c = b.ravel()

In [49]:
np.argsort(c) # возвращает порядковый номер индексов, умеет в оси

array([12,  8,  7,  1,  5,  6,  4,  0,  9, 14, 10, 16,  2, 15, 17, 11, 19,
        3, 13, 18])

In [50]:
np.sort(c) == c[np.argsort(c)]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [51]:
np.argmax(c) # индекс максимального умеет по осям

18

In [52]:
np.argmin(c) # индекс минимального умеет по осям

8

In [53]:
np.linalg.norm(b, axis=1) # длина вектора

array([353.52934815, 165.82520918, 532.7635498 , 844.78517979])

In [54]:
np.linalg.inv(b) # обратная матрица, только для квадратных

LinAlgError: ignored

In [55]:
d = np.arange(16)

In [56]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
d = d.reshape(4, 4) # произведение измерений в решейп должно быть равно количеству элементов

In [58]:
d.reshape(4, 5)

ValueError: ignored

In [59]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
b

array([[ 99,  55, 212, 242,  93],
       [ 60,  92,  47,   0, 115],
       [192, 227,   0, 420, 138],
       [213, 207, 222, 724, 228]])

In [62]:
b[:, None, :].shape

(4, 1, 5)

In [61]:
b.shape

(4, 5)

In [63]:
b + np.arange(5)[None, :]

array([[ 99,  56, 214, 245,  97],
       [ 60,  93,  49,   3, 119],
       [192, 228,   2, 423, 142],
       [213, 208, 224, 727, 232]])

In [64]:
b + np.arange(4)

ValueError: ignored

In [66]:
b + np.arange(4)[:, None]

array([[ 99,  55, 212, 242,  93],
       [ 61,  93,  48,   1, 116],
       [194, 229,   2, 422, 140],
       [216, 210, 225, 727, 231]])

In [67]:
a.shape

(512, 640, 3)

In [72]:
a.reshape(-1, 3).shape # засунет все оставшиеся измерения

(327680, 3)

In [70]:
b.reshape(2, 2, -1)

array([[[ 99,  55, 212, 242,  93],
        [ 60,  92,  47,   0, 115]],

       [[192, 227,   0, 420, 138],
        [213, 207, 222, 724, 228]]])

In [71]:
b.reshape(2, -1, 2)

array([[[ 99,  55],
        [212, 242],
        [ 93,  60],
        [ 92,  47],
        [  0, 115]],

       [[192, 227],
        [  0, 420],
        [138, 213],
        [207, 222],
        [724, 228]]])

In [ ]:
b.astype(np.float64)

In [ ]:
import torch

In [ ]:
torch.arange(10)

In [ ]:
torch.arange(10).float().mean()

In [ ]:
torch.arange(10).view(2, -1)

In [ ]:
t = np.array(["asd", "412"])

In [ ]:
b.shape

In [ ]:
c = np.arange(12)

In [ ]:
c = c.reshape(4, 3)

In [ ]:
np.concatenate([b, c], axis=1)