In [1]:
import torch
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(10)
c = np.arange(12).reshape(4, 3)
d = np.arange(9).reshape(3, 3)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a * b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
a[:, None] * b[None, :] # из векторов матрица

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [7]:
c *= 2

In [8]:
c

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [9]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
c[:, None, :] * d[None, :, :] # из двумерной получаем трехмерную 3 измерение должно совпадать

array([[[  0,   2,   8],
        [  0,   8,  20],
        [  0,  14,  32]],

       [[  0,   8,  20],
        [ 18,  32,  50],
        [ 36,  56,  80]],

       [[  0,  14,  32],
        [ 36,  56,  80],
        [ 72,  98, 128]],

       [[  0,  20,  44],
        [ 54,  80, 110],
        [108, 140, 176]]])

In [11]:
t = np.ones(8)

In [12]:
t

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
t = np.ones((3, 3))

In [14]:
t

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
t = np.zeros(8)

In [16]:
t

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
t = np.zeros((3, 3))

In [18]:
t

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
t = np.full(8, 5)

In [20]:
t

array([5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
t = np.full((3, 3), 5)

In [22]:
t

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
np.eye(2) # матрица I размером aргумент * аргумент

array([[1., 0.],
       [0., 1.]])

In [24]:
k = np.random.randint(0, 255, size=(480, 640))

In [25]:
a.dot(b) == a @ b # скалярное произведение

True

In [26]:
a = torch.from_numpy(a)

In [27]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b = torch.from_numpy(b)

In [29]:
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a @ b

tensor(285)

In [31]:
a + b

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
a * b

tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [33]:
a.view(2, 5) # вместо reshape

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
a.matmul(b) # скалярное произведение

tensor(285)

In [35]:
c @ d

array([[ 30,  36,  42],
       [ 84, 108, 132],
       [138, 180, 222],
       [192, 252, 312]])

In [36]:
c = torch.from_numpy(c)
d = torch.from_numpy(d)

In [37]:
c @ d

tensor([[ 30,  36,  42],
        [ 84, 108, 132],
        [138, 180, 222],
        [192, 252, 312]])

In [38]:
d = torch.rand(2, 3, 4).float()

In [39]:
c = c.view(2, 2, 3).float()

In [40]:
c.bmm(d) # поматричное скалярное умножение

tensor([[[ 3.1260,  3.0519,  1.6844,  1.2189],
         [10.1534, 13.0500,  8.7832,  6.6797]],

        [[22.6162, 25.0887, 23.7689, 25.0312],
         [32.7450, 36.1336, 33.3722, 35.5404]]])

In [41]:
c

tensor([[[ 0.,  2.,  4.],
         [ 6.,  8., 10.]],

        [[12., 14., 16.],
         [18., 20., 22.]]])

In [42]:
d

tensor([[[0.0480, 0.7615, 0.4777, 0.3541],
         [0.6834, 0.2838, 0.5686, 0.5025],
         [0.4398, 0.6211, 0.1368, 0.0535]],

        [[0.6718, 0.7720, 0.2946, 0.3974],
         [0.8533, 0.6381, 0.3309, 0.7019],
         [0.1630, 0.4307, 0.9751, 0.6523]]])

In [43]:
c = torch.rand(4096, 4096)
d = torch.rand(4096, 4096)

In [44]:
%%time
c @ d

CPU times: user 1.66 s, sys: 16 ms, total: 1.68 s
Wall time: 449 ms


tensor([[1000.5043, 1002.7506, 1016.3815,  ..., 1021.7222,  996.3809,
         1022.0295],
        [1004.1023,  989.6271, 1019.1122,  ..., 1027.7609,  989.2344,
         1020.8045],
        [1013.7366, 1013.6102, 1022.3150,  ..., 1045.7231,  997.6496,
         1024.9705],
        ...,
        [1010.2330, 1010.4396, 1034.6396,  ..., 1042.2598,  991.3449,
         1026.9644],
        [1009.0648, 1000.8672, 1024.1233,  ..., 1027.8341,  996.4392,
         1025.4424],
        [1019.1187, 1015.5603, 1022.6256,  ..., 1043.6481, 1000.3350,
         1025.2764]])

In [45]:
c = c.cuda()
d = d.cuda()

In [46]:
%%time
c @ d

CPU times: user 27.9 ms, sys: 4.76 ms, total: 32.7 ms
Wall time: 98.8 ms


tensor([[1000.5048, 1002.7504, 1016.3809,  ..., 1021.7224,  996.3816,
         1022.0288],
        [1004.1021,  989.6268, 1019.1138,  ..., 1027.7621,  989.2343,
         1020.8036],
        [1013.7377, 1013.6097, 1022.3154,  ..., 1045.7219,  997.6493,
         1024.9708],
        ...,
        [1010.2337, 1010.4394, 1034.6403,  ..., 1042.2598,  991.3443,
         1026.9642],
        [1009.0652, 1000.8668, 1024.1230,  ..., 1027.8328,  996.4389,
         1025.4429],
        [1019.1188, 1015.5598, 1022.6263,  ..., 1043.6490, 1000.3340,
         1025.2764]], device='cuda:0')

In [47]:
c = torch.randint(0, 255, size=(480, 640))

In [48]:
torch.mode(c.flatten()) # самый частый элемент в массиве

torch.return_types.mode(
values=tensor(238),
indices=tensor(134496))