# Numpy

numpy - это библиотека для работы с многомерными массивами

In [1]:
import numpy as np # стандартная запись импорта numpy

In [2]:
np.random.seed(42) # фиксация генератора рандомных чисел (необходимо для повторяемости)

## Создание массива

основной класс данной библиотеки np.ndarray 

данный массив может иметь любую размерность и его возможно создать с помощью списка и вызова np.array

In [3]:
a = np.array([1, 2])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape # размерность массива

(2,)

In [6]:
a.ndim # количество измерений массива

1

In [7]:
a = np.array([[1, 2], [3, 4]])

In [8]:
a.shape

(2, 2)

In [9]:
a.ndim

2

при создании многомерных массивов что все внутренние размерности у вас одинаковы, иначе будет создан массив списков, вместо массива чисел

In [10]:
a.dtype # тип переменных внутри массива

dtype('int32')

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
a = np.array([[1, 2], [3]])

In [13]:
a.dtype

dtype('O')

In [14]:
a

array([list([1, 2]), list([3])], dtype=object)

In [15]:
a = np.array([[1,2], [3, 4]], dtype=np.float32)

In [16]:
a

array([[1., 2.],
       [3., 4.]], dtype=float32)

массив так же можно создать с помощью других встроенных функций

In [17]:
a = np.arange(1, 10, 2) # создает массив от 1го параметра до 2го параметра (не включительно) с шагом 3го параметра

In [18]:
a # np.arange() - часто полезен для отрисовки графиков и индексирования

array([1, 3, 5, 7, 9])

In [19]:
b = np.array([[1, 2], [3, 4], [5, 6]])

In [20]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
i = np.arange(0, b.shape[0], 1)

In [22]:
index = np.random.choice(i, 2, replace=False) # случайный выбор из итерируемого объекта

In [23]:
index

array([0, 1])

In [24]:
b[index]

array([[1, 2],
       [3, 4]])

In [25]:
a = np.zeros((2, 2)) # создает массив из нулей указанной размерности

In [26]:
a # полезен при накоплении суммы

array([[0., 0.],
       [0., 0.]])

In [27]:
for i in range(5):
    r = np.random.rand(2, 2) # массив случайных чисел, размерность каждого измерения указывается раздельно
    a += r

In [28]:
a

array([[2.55187695, 1.42443203],
       [2.90937813, 2.50567143]])

In [29]:
a = np.ones((2, 2)) # создает массив из едениц указанной размерности

In [30]:
a # полезен при накоплении произведения

array([[1., 1.],
       [1., 1.]])

In [31]:
for i in range(5):
    r = np.random.rand(2, 2)
    a *= r

In [32]:
a

array([[0.00047152, 0.02341602],
       [0.01143103, 0.00065337]])

In [33]:
a = np.empty((0, 2)) # создает пустой массив указанной размерности

In [34]:
a # полезен для накопления данных в массиве

array([], shape=(0, 2), dtype=float64)

In [35]:
for i in range(5):
    r = np.random.rand(1, 2)
    a = np.append(a, r, axis=0) # присоедененяет 2 массива вдоль оси

In [36]:
a

array([[0.49517691, 0.03438852],
       [0.9093204 , 0.25877998],
       [0.66252228, 0.31171108],
       [0.52006802, 0.54671028],
       [0.18485446, 0.96958463]])

np.zeros_like, np.ones_like, np.empty_like - то же самое что и np.zeros, np.ones, np.empty только размерность берется из переданного массива

np.ndarray - https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

np.arange - https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

np.zeros - https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html

np.ones - https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones

np.emty - https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html#numpy.empty

np.zeros_like - https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like

np.ones_like - https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like

np.empty_like - https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like

np.random.rand - https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.mtrand.RandomState.rand.html#numpy.random.mtrand.RandomState.rand

np.append - https://docs.scipy.org/doc/numpy/reference/generated/numpy.append.html

## Индексирование массива

In [37]:
# метод reshape преобразует массив в указанную размерность
# количество элементов в массиве должно быть равно произведению размерностей
a = np.arange(0, 18, 1).reshape(3, 2, 3)

In [38]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

индексация проводится по осям вдоль каждого измерения:

**1D**

<img src="./img/axis1d.png">

**2D**

<img src="./img/axis2d.png">

**3D**

<img src="./img/axis3d.png">

In [39]:
a[0, 1, 1] # берем элемент находящийся в конкретном положении

4

In [40]:
a[0, :, 0] # берем всю первую ось

array([0, 3])

In [41]:
a[:, 0, :] # срез массива вдоль нулевой и второй оси

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [42]:
a[0:2, 0, 0:2] # мы можем так же индексировать срезами вдоль осей

array([[0, 1],
       [6, 7]])

In [43]:
a[0:3:2, 0, 0:2] # или задавать шаг

array([[ 0,  1],
       [12, 13]])

In [44]:
a[[0, 2], 1, [1, 2]] # индексы могут быть сами в виде массивов

array([ 4, 17])

In [45]:
a[a < 7] # особый вид индекса - это логический индекс

array([0, 1, 2, 3, 4, 5, 6])

In [46]:
a[(a % 2).astype(np.bool)] # astype конвертирует все элементы массива в указаный тип

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

индексирование массива - https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

## Математические операции с массивами

In [47]:
# с численными массивами можно выполнять различные операции
a = np.arange(6).reshape(2, 3)

In [48]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
a + 1 # сложение со скаляром

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a - 1 # вычитание со скаляром

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [51]:
a * 2 # умножение на скаляр

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [52]:
a / 2 # деление на скаляр

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5]])

In [53]:
a ** 2 # возведение в степень

array([[ 0,  1,  4],
       [ 9, 16, 25]], dtype=int32)

In [54]:
np.power(a, 2) # тоже возведение в степень

array([[ 0,  1,  4],
       [ 9, 16, 25]], dtype=int32)

In [55]:
np.exp(a) # степень экспоненты

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [56]:
np.log(a) # логарифм - логарифм нуля будет посчитан как минус бесконечность

c:\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791]])

In [57]:
np.log1p(a) # логарифм от элемента + 1, используется чтобы значение в 0 было определено

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [58]:
np.expm1(np.log1p(a)) # экспонента минус 1, обратная функция к log1p

array([[0., 1., 2.],
       [3., 4., 5.]])

In [59]:
b = np.ones((2, 3))

In [60]:
a + b # массивы одинаковой размерности можно складывать

array([[1., 2., 3.],
       [4., 5., 6.]])

In [61]:
a - b # вычитать

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [62]:
b = np.arange(1, 7).reshape(2, 3)

In [63]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]


In [64]:
a * b # умножать поэлементно

array([[ 0,  2,  6],
       [12, 20, 30]])

In [65]:
a / b # делить поэлементно

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333]])

In [66]:
b.T # транспонирование массива (меняем местами оси)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
# матричное умножение, возможно лишь когда размерность: 
# последней оси 1го массива равна размерности предпоследней оси 2го массива
a.dot(b.T) 

array([[ 8, 17],
       [26, 62]])

In [68]:
a = np.arange(36).reshape(3, 2, 3, 2)

In [69]:
b = np.arange(36).reshape(2, 3, 2, 3)

In [70]:
a.dot(b)

array([[[[[[   3,    4,    5],
           [   9,   10,   11],
           [  15,   16,   17]],

          [[  21,   22,   23],
           [  27,   28,   29],
           [  33,   34,   35]]],


         [[[   9,   14,   19],
           [  39,   44,   49],
           [  69,   74,   79]],

          [[  99,  104,  109],
           [ 129,  134,  139],
           [ 159,  164,  169]]],


         [[[  15,   24,   33],
           [  69,   78,   87],
           [ 123,  132,  141]],

          [[ 177,  186,  195],
           [ 231,  240,  249],
           [ 285,  294,  303]]]],



        [[[[  21,   34,   47],
           [  99,  112,  125],
           [ 177,  190,  203]],

          [[ 255,  268,  281],
           [ 333,  346,  359],
           [ 411,  424,  437]]],


         [[[  27,   44,   61],
           [ 129,  146,  163],
           [ 231,  248,  265]],

          [[ 333,  350,  367],
           [ 435,  452,  469],
           [ 537,  554,  571]]],


         [[[  33,   54,   75],
       

набор функций для вычислений https://docs.scipy.org/doc/numpy/reference/routines.math.html

## Статистики массива

In [71]:
a = np.arange(9, 0, -1).reshape(3, 3)

In [72]:
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [73]:
a.sum() # сумма всех элементов

45

In [74]:
a.sum(axis=0) # сумма вдоль оси, все статистики можно использовать со специфированной осью

array([18, 15, 12])

In [75]:
a.mean() # среднее

5.0

In [76]:
a.mean(axis=1)

array([8., 5., 2.])

In [77]:
a.max() # максимум

9

In [78]:
a.argmax(axis=1) # индекс максимального элемента

array([0, 0, 0], dtype=int64)

In [79]:
a.min() # минимум

1

In [80]:
a.argmin() # если в оси находится целлый массив, индекс берется для минимального элемента array.ravel()

8

In [81]:
a.ravel() # разворачивает массив в одну ось

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [82]:
a.var(ddof=0) # дисперсия, ddof по умолчанию равен 0

6.666666666666667

In [83]:
a.std(ddof=1) # стандартное отклонение, ddof определяет что оценка несмещенная

2.7386127875258306

In [84]:
np.median(a) # медиана массива

5.0

In [85]:
np.quantile(a, 0.25) # 25й квантиль

3.0

дисперсия https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D1%81%D0%BF%D0%B5%D1%80%D1%81%D0%B8%D1%8F_%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D0%BE%D0%B9_%D0%B2%D0%B5%D0%BB%D0%B8%D1%87%D0%B8%D0%BD%D1%8B

стадартное отклонение https://ru.wikipedia.org/wiki/%D0%A1%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%BA%D0%B2%D0%B0%D0%B4%D1%80%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%BE%D1%82%D0%BA%D0%BB%D0%BE%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5

статистичекие функции
https://docs.scipy.org/doc/numpy/reference/routines.statistics.html

## Другие полезные функции

In [86]:
a

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [87]:
np.sort(a) # сортировка массива по умолчанию для последней оси

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [88]:
np.sort(a, axis=0)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [89]:
np.argsort(a) # порядок индексов в отсортированном массиве

array([[2, 1, 0],
       [2, 1, 0],
       [2, 1, 0]], dtype=int64)

In [90]:
np.where(a > 2) # возвращает индексы элеметов логического условия

(array([0, 0, 0, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0], dtype=int64))

In [91]:
np.where(a > 2, 2, -2) # возможно определить величины для True, False - вернется массив

array([[ 2,  2,  2],
       [ 2,  2,  2],
       [ 2, -2, -2]])

In [92]:
np.linalg.norm(a) # l2 норма массива

16.881943016134134

In [93]:
np.linalg.norm(a, axis=1) # оси так же могут быть специфированы

array([13.92838828,  8.77496439,  3.74165739])

In [94]:
a += np.eye(3, dtype=np.int32) # np.eye еденичная матрица где на главной диагонали находятся еденицы, в остальных местах нули

In [95]:
np.linalg.inv(a) # обратная матрица, матрица не должна быть линейно зависимой

array([[-2.00000000e+00,  1.00000000e+00,  5.00000000e+00],
       [-6.47630098e-16,  5.00000000e-01, -1.00000000e+00],
       [ 3.00000000e+00, -2.00000000e+00, -6.00000000e+00]])

In [96]:
# np.round округляет элементы до указанного знака 
# умножение матрицы и обратной дает еденичную
np.round(a.dot(np.linalg.inv(a)), 10) 

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

np.sort https://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

np.argsort https://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html

np.where https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

np.linalg.norm https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html#numpy.linalg.norm

np.linalg.inv https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv

## Полезные материалы

numpy manual https://docs.scipy.org/doc/numpy/index.html

матричное умножение https://ru.wikipedia.org/wiki/%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86

обратная матрица https://ru.wikipedia.org/wiki/%D0%9E%D0%B1%D1%80%D0%B0%D1%82%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0

еденичная матрица https://ru.wikipedia.org/wiki/%D0%95%D0%B4%D0%B8%D0%BD%D0%B8%D1%87%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0